// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaNivelacion.Models;

#nullable disable

namespace PruebaNivelacion.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20231218160641_InitialMig")]
    partial class InitialMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaNivelacion.Models.BookModel", b =>
                {
                    b.Property<int>("Id_libro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_libro"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campos_auditoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_lanzamiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_libro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_libro");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
